-- Create leads table
CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone_number TEXT,
  address TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster searches
CREATE INDEX idx_leads_name ON leads USING GIN (name gin_trgm_ops);
CREATE INDEX idx_leads_email ON leads USING GIN (email gin_trgm_ops);
CREATE INDEX idx_leads_phone ON leads USING GIN (phone_number gin_trgm_ops);
CREATE INDEX idx_leads_address ON leads USING GIN (address gin_trgm_ops);
CREATE INDEX idx_leads_notes ON leads USING GIN (notes gin_trgm_ops);

-- Add row level security
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Create policy that only allows authenticated users to see their own organization's leads
CREATE POLICY "Users can view leads" ON leads FOR SELECT
  USING (auth.role() = 'authenticated');

-- Create policy that only allows authenticated users to insert leads
CREATE POLICY "Users can insert leads" ON leads FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Create policy that only allows authenticated users to update their own organization's leads
CREATE POLICY "Users can update leads" ON leads FOR UPDATE
  USING (auth.role() = 'authenticated');

-- Create policy that only allows authenticated users to delete their own organization's leads
CREATE POLICY "Users can delete leads" ON leads FOR DELETE
  USING (auth.role() = 'authenticated');

-- Create trigger to update the updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_leads_updated_at
BEFORE UPDATE ON leads
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Sample data
INSERT INTO leads (name, email, phone_number, address, notes)
VALUES 
  ('Jane Smith', 'jane.smith@example.com', '(555) 123-4567', '123 Main St, Anytown, CA 12345', 'Interested in enterprise plan. Follow up next week.'),
  ('John Doe', 'john.doe@example.com', '(555) 987-6543', '456 Oak Ave, Springfield, IL 67890', 'Currently using competitor product. Price sensitive.'),
  ('Maria Garcia', 'maria.garcia@example.com', '(555) 456-7890', '789 Pine Rd, Metropolis, NY 54321', 'Requested demo. High potential value customer.');
